config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'home', to: 'welcome#home', as: :strona_domowa
  get 'color', to: 'welcome#color', as: :strona_color

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HTMLCss2015</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>

<%= yield %>

</body>
</html>

app/views/welcome/color.html.erb
<div id="color">
  <h1>Briardy</h1>
  <p class="credits">napisala Ivy Duckett</p>
  <p class="intro"><a class="breed" href="http://www.google.pl">Briard</a>
  ,inaczej owczarek francuski briard, jest duzym psem pasterskim tradycyjnie uzywanym do wypasania...</p>

</div>

app/views/welcome/home.html.erb
<h1>Ala ma kota</h1>
<p>
  <%= link_to 'Zerknij na strone testowa', strona_domowa_path %>
</p>

app/views/welcome/index.html.erb
<div id="logo">
  <img src="images/logo.gif" alt="Analogowi specjaliści">
</div>
<ul id="navigation">
  <li><a href="#" class="on">Początek</a></li>
  <li><a href="#">Sprzedaż</a></li>
  <li><a href="#">Naprawy</a></li>
  <li><a href="#">O nas</a></li>
  <li><a href="#">Kontakt</a></li>
</ul>
<p>
  <img src="<%= asset_path('keys.jpg')%> " alt="Fender Rhodes, Hohner Clavinet oraz Wurlitzer EP200">
</p>
<p>
  Specjalizujemy się w sprzedaży oraz naprawach klasycznych instrumentów klawiszowych, a w szczególności: Fender Rhodes, Wurlitzer EP200 oraz Hohner Clavinet.
</p>
    